package android.support.customtabs.browseractions;

import android.content.ContentResolver;
import android.content.Context;
import android.content.pm.ResolveInfo;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.AsyncTask;
import android.os.ParcelFileDescriptor;
import android.util.Log;

import java.io.FileDescriptor;
import java.io.FileNotFoundException;

/**
 * The {@link AsyncTask} to access an image from an uri generated by {@link
 * BrowserServiceFileProvider.generateUri(Context, Bitmap, String, int, List<ResolveInfo>)}.
 */
public class BrowserServiceImageReadTask<Uri, Void, Bitmap> extends AsyncTask<Uri, Void, Bitmap> {
    private static final String TAG = "BrowserServiceImageReadTask";
    private final Context mContext;

    public BrowserServiceImageReadTask(Context context) {
        super();
        mContext = context;
    }

    @Override
    protected Bitmap doInBackground(Uri... params) {
        ContentResolver resolver = mContext.getContentResolver();
        try {
            ParcelFileDescriptor pdf =
                    resolver.openFileDescriptor((android.net.Uri) params[0], "r");
            if (pdf == null) return null;
            FileDescriptor fd = pdf.getFileDescriptor();
            return (Bitmap) BitmapFactory.decodeFileDescriptor(fd);
        } catch (FileNotFoundException e) {
            Log.e(TAG, "Fail to read bitmap", e);
        }
        return null;
    }

    @Override
    protected void onPostExecute(Bitmap bm) {}
}