package android.support.customtabs.browseractions;

import android.content.ContentResolver;
import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.AsyncTask;
import android.os.ParcelFileDescriptor;
import android.util.Log;

import java.io.FileDescriptor;
import java.io.FileNotFoundException;

/**
 * The {@link AsyncTask} to access an image from an uri generated by {@link
 * BrowserServiceFileProvider.generateUri(Context, Bitmap, String, int, List<ResolveInfo>)}.
 */
public class BrowserServiceImageReadTask extends AsyncTask<Uri, Void, Bitmap> {
    private static final String TAG = "BrowserServiceImageReadTask";
    private final ContentResolver mResolver;

    public BrowserServiceImageReadTask(Context context) {
        super();
        mResolver = context.getContentResolver();
    }

    @Override
    protected Bitmap doInBackground(Uri... params) {
        try {
            ParcelFileDescriptor descriptor = mResolver.openFileDescriptor(params[0], "r");
            if (descriptor == null) return null;
            FileDescriptor fileDescriptor = descriptor.getFileDescriptor();
            return BitmapFactory.decodeFileDescriptor(fileDescriptor);
        } catch (FileNotFoundException e) {
            Log.e(TAG, "Failed to read bitmap", e);
        }
        return null;
    }

    @Override
    protected void onPostExecute(Bitmap bitmap) {}
}